-- Bảng dân tộc
CREATE TABLE IF NOT EXISTS `NLCN`.`DAN_TOC` (
  `TEN_DAN_TOC` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `TEN_DAN_TOC_UNIQUE` (`TEN_DAN_TOC` ASC) VISIBLE,
  PRIMARY KEY (`TEN_DAN_TOC`))
ENGINE = InnoDB;
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Kinh');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Tày');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Thái');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Hoa');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Khơ-me');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Mường');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Nùng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('HMông');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Dao');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Gia-rai');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Ngái');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Ê-đê');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Ba na');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Xơ-đăng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Sán Chay');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Cơ-ho');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Chăm');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Sán Dìu');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Hrê');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Mnông');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Ra-glai');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Xtiêng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Bru-Vân Kiều');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Thổ');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Giáy');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Cơ-tu');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Gié Triêng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Mạ');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Khơ-mú');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Co');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Tà-ôi');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Chơ-ro');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Kháng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Xinh-mun');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Hà Nhì');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Chu-ru');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Lào');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('La Chí');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('La Ha');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Phù Lá');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('La Hủ');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Lự');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Lô Lô');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Chứt');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Mảng');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Pà Thẻn');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Co Lao');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Cống');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Bố Y');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Si La');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Pu Péo');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Brâu');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Ơ-đu');
INSERT INTO `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`) VALUES ('Rơ-măm');
-- Bảng Quận huyện
CREATE TABLE IF NOT EXISTS `NLCN`.`QUAN_HUYEN` (
  `MA_QUAN_HUYEN` VARCHAR(2) NOT NULL,
  `TEN_QUAN_HUYEN` VARCHAR(45) NULL,
  PRIMARY KEY (`MA_QUAN_HUYEN`),
  UNIQUE INDEX `MA_QUAN_HUYEN_UNIQUE` (`MA_QUAN_HUYEN` ASC) VISIBLE,
  UNIQUE INDEX `TEN_QUAN_HUYEN_UNIQUE` (`TEN_QUAN_HUYEN` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('01', 'Quận Ninh Kiều');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('02', 'Quận Bình Thủy');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('03', 'Quận Cái Răng');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('04', 'Quận Ô Môn');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('05', 'Huyện Phong Điền');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('06', 'Huyện Cờ Đỏ');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('07', 'Huyện Vĩnh Thạnh');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('08', 'Quận Thốt Nốt');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('09', 'Huyện Thới Lai');
INSERT INTO `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`, `TEN_QUAN_HUYEN`) VALUES ('99', 'Ngoài TP Cần Thơ');
-- Bảng Đối tượng ưu tiên
CREATE TABLE IF NOT EXISTS `NLCN`.`DT_UU_TIEN` (
  `MA_DT_UU_TIEN` INT NOT NULL,
  `TEN_DT_UU_TIEN` VARCHAR(200) NOT NULL,
  `DIEM_CONG` DOUBLE NOT NULL,
  PRIMARY KEY (`MA_DT_UU_TIEN`),
  UNIQUE INDEX `MA_DT_UU_TIEN_UNIQUE` (`MA_DT_UU_TIEN` ASC) VISIBLE,
  UNIQUE INDEX `TEN_DT_UU_TIEN_UNIQUE` (`TEN_DT_UU_TIEN` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (101, 'Con của liệt sĩ', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (102, 'Con của thương binh, bệnh binh mất sức lao động 81% trở lên', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (103, 'Con của người được cấp \"GCN người hưởng chính sách như thương binh\" mà người được cấp GCN bị suy giảm khả năng lao động 81% trở lên', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (104, 'Con của người hoạt động kháng chiến bị nhiễm chất độc hóa học', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (105, 'Con của người hoạt động cách mạng trước ngày 01/01/1945', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (106, 'Con của người hoạt động cách mạng từ ngày 01/01/1945 đến ngày khởi nghĩa tháng 8 năm 1945', 2.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (201, 'Con của AHLLVT, con của AHLĐ, con của Bà mẹ Việt Nam anh hùng', 1.5);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (202, 'Con của thương binh, bệnh binh mất sức lao động dưới 81%', 1.5);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (203, 'Con của người được cấp \"GCN người hưởng chính sách như thương binh\" mà người được cấp GCN bị suy giảm khả năng lao động dưới 81%', 1.5);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (301, 'Người có cha hoặc mẹ là người dân tộc thiểu số', 1.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (302, 'Người dân tộc thiểu số', 1.0);
INSERT INTO `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`, `TEN_DT_UU_TIEN`, `DIEM_CONG`) VALUES (303, 'Người học đang sinh sống, học tập ở các vùng có điều kiện KT-XH đặc biệt khó khăn', 1.0);
-- Bảng Đối tượng khuyến khích
CREATE TABLE IF NOT EXISTS `NLCN`.`DT_KHUYEN_KHICH` (
  `MA_DT_KHUYEN_KHICH` INT NOT NULL,
  `TEN_DT_KHUYEN_KHICH` VARCHAR(100) NOT NULL,
  `DIEM_CONG` DOUBLE NOT NULL,
  PRIMARY KEY (`MA_DT_KHUYEN_KHICH`),
  UNIQUE INDEX `MA_DT_KHUYEN_KHICH_UNIQUE` (`MA_DT_KHUYEN_KHICH` ASC) VISIBLE,
  UNIQUE INDEX `TEN_DT_KHUYEN_KHICH_UNIQUE` (`TEN_DT_KHUYEN_KHICH` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`DT_KHUYEN_KHICH` (`MA_DT_KHUYEN_KHICH`, `TEN_DT_KHUYEN_KHICH`, `DIEM_CONG`) VALUES (1, 'Giải Nhất Học sinh giỏi THCS cấp tỉnh/thành phố', 1.5);
INSERT INTO `NLCN`.`DT_KHUYEN_KHICH` (`MA_DT_KHUYEN_KHICH`, `TEN_DT_KHUYEN_KHICH`, `DIEM_CONG`) VALUES (2, 'Giải Nhì Học sinh giỏi THCS cấp tỉnh/thành phố', 1.0);
INSERT INTO `NLCN`.`DT_KHUYEN_KHICH` (`MA_DT_KHUYEN_KHICH`, `TEN_DT_KHUYEN_KHICH`, `DIEM_CONG`) VALUES (3, 'Giải Ba Học sinh giỏi THCS cấp tỉnh/thành phố', 0.5);
-- Bảng Trường THCS
CREATE TABLE IF NOT EXISTS `NLCN`.`TRUONG_THCS` (
  `MA_THCS` VARCHAR(5) NOT NULL,
  `TEN_THCS` VARCHAR(100) NULL,
  `MA_QUAN_HUYEN` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`MA_THCS`),
  INDEX `fk_TRUONG_THCS_QUAN_HUYEN_idx` (`MA_QUAN_HUYEN` ASC) VISIBLE,
  UNIQUE INDEX `MA_THCS_UNIQUE` (`MA_THCS` ASC) VISIBLE,
  UNIQUE INDEX `TEN_THCS_UNIQUE` (`TEN_THCS` ASC) VISIBLE,
  CONSTRAINT `fk_TRUONG_THCS_QUAN_HUYEN`
    FOREIGN KEY (`MA_QUAN_HUYEN`)
    REFERENCES `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01001, 'THCS An Hòa 1', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01002, 'THCS An Hòa 2', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01003, 'THCS An Khánh', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01004, 'THCS An Lạc', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01005, 'THCS Chu Văn An', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01006, 'THCS Đoàn Thị Điểm', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01007, 'THCS Huỳnh Thúc Kháng', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01008, 'THCS Lương Thế Vinh', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01009, 'THCS Thới Bình', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01010, 'THCS Trần Hưng Đạo', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01011, 'THCS Trần Ngọc Quế', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (01012, 'THCS An Bình', '01');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02001, 'THCS An Thới', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02002, 'THCS Trà An', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02003, 'THCS Bình Thủy', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02004, 'THCS Long Hòa', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02005, 'THCS Long Tuyền', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (02006, 'THCS Thới An Đông', '02');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (03001, 'THCS Hưng Phú', '03');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (03002, 'THCS Hưng Thạnh', '03');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (03003, 'THCS Lê Bình', '03');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (03004, 'THCS Phú Thứ', '03');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (03005, 'THCS Thường Thạnh', '03');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (04001, 'THCS Châu Văn Liêm', '04');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (04002, 'THCS Lê Lợi', '04');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (04003, 'THCS Ngô Quyền', '04');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (04004, 'THCS Nguyễn Trãi', '04');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (04005, 'THCS Thới Long', '04');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05001, 'THCS Nhơn Ái', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05002, 'THCS Giai Xuân', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05003, 'THCS Mỹ Khánh', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05004, 'THCS Nhơn Nghĩa', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05005, 'THCS Thị trấn Phong Điền', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05006, 'THCS Trường Long', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (05007, 'THCS Tân Thới', '05');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06001, 'THCS Đông Hiệp', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06002, 'THCS Thị trấn Cờ Đỏ', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06003, 'THCS Thới Xuân', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06004, 'THCS Thạnh Phú 1', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06005, 'THCS Thạnh Phú 2', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06006, 'THCS Trung Hưng', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06007, 'THCS Trung An', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06008, 'THCS Trung Thạnh', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (07001, 'THCS Thị trấn Vĩnh Thạnh', '07');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (07002, 'THCS Thạnh Mỹ', '07');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (07003, 'THCS Thạnh Quới', '07');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (07004, 'THCS Vĩnh Trinh', '07');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08001, 'THCS Tân Lộc', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08002, 'THCS Thuận Hưng', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08003, 'THCS Thốt Nốt', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08004, 'THCS Thới Thuận', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08005, 'THCS Trung Kiên', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08006, 'THCS Tân Hưng', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08007, 'THCS Trung Nhứt', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08008, 'THCS và THPT Tân Lộc', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (08009, 'THCS và THPT Thới Thuận', '08');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09001, 'THCS Trường Thành 1', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09002, 'THCS Trường Thành 2', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09003, 'THCS Trường Xuân', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09004, 'THCS Viện Lúa', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09005, 'THCS Đông Bình', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09006, 'THCS Đông Thuận', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09007, 'THCS Định Môn', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09008, 'THCS và THPT Trường Xuân', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (09009, 'THCS và THPT Thới Thạnh', '09');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (07005, 'THCS và THPT Thạnh Thắng', '07');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (06009, 'THCS và THPT Trần Ngọc Hoằng', '06');
INSERT INTO `NLCN`.`TRUONG_THCS` (`MA_THCS`, `TEN_THCS`, `MA_QUAN_HUYEN`) VALUES (99999, 'Ngoài TP Cần Thơ', '99');
-- Bảng Trường THPT
CREATE TABLE IF NOT EXISTS `NLCN`.`TRUONG_THPT` (
  `MA_THPT` VARCHAR(3) NOT NULL,
  `TEN_THPT` VARCHAR(100) NOT NULL,
  `DIA_CHI` VARCHAR(200) NOT NULL,
  `MA_QUAN_HUYEN` VARCHAR(2) NOT NULL,
  `CHI_TIEU` INT NULL,
  PRIMARY KEY (`MA_THPT`),
  INDEX `fk_TRUONG_THPT_QUAN_HUYEN1_idx` (`MA_QUAN_HUYEN` ASC) VISIBLE,
  UNIQUE INDEX `MA_THPT_UNIQUE` (`MA_THPT` ASC) VISIBLE,
  UNIQUE INDEX `TEN_THPT_UNIQUE` (`TEN_THPT` ASC) VISIBLE,
  CONSTRAINT `fk_TRUONG_THPT_QUAN_HUYEN1`
    FOREIGN KEY (`MA_QUAN_HUYEN`)
    REFERENCES `NLCN`.`QUAN_HUYEN` (`MA_QUAN_HUYEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (002, 'THPT Châu Văn Liêm', '58 Ngô Quyền, phường An Cư, quận Ninh Kiều, TP Cần Thơ', '01', 585);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (003, 'THPT Nguyễn Việt Hồng', '568 đường 3/2, khu vực 1, phường An Bình, quận Ninh Kiều, TP Cần Thơ', '01', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (004, 'THPT Phan Ngọc Hiển', '33 Xô Viết Nghệ Tĩnh, phường An Cư, quận Ninh Kiều, TP Cần Thơ', '01', 520);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (063, 'THPT Thực hành sư phạm - ĐHCT', 'Khu II Đại học Cần Thơ, phường Xuân Khánh, quận Ninh Kiều, TP Cần Thơ', '01', 216);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (080, 'THPT An Khánh', '106 Trần Văn Long, KDC Thới Nhựt 2, phường An Khánh, quận Ninh Kiều, TP Cần Thơ', '01', 480);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (012, 'THPT Bùi Hữu Nghĩa', '55 Cách mạng tháng Tám, phường An Thới, quận Bình Thủy, TP Cần Thơ', '02', 585);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (014, 'THPT Bình Thủy', 'KDC Ngân Thuận, phường Bình Thuỷ, quận Bình Thủy, TP Cần Thơ', '02', 630);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (015, 'THPT Trần Đại Nghĩa', 'Đường A3, KDC Hưng Phú 1, phường Hưng Phú, quận Cái Răng, TP Cần Thơ', '03', 450);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (018, 'THPT Nguyễn Việt Dũng', '161 Lê Bình, phường Lê Bình, quận Cái Răng, TP Cần Thơ', '03', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (013, 'THPT Chuyên Lý Tự Trọng', 'Khu vực 2, phường Hưng Thạnh, quận Cái Răng, TP Cần Thơ', '03', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (021, 'THPT Lưu Hữu Phước', 'Khu vực 15, phường Châu Văn Liêm, quận Ô Môn, TP Cần Thơ', '04', 470);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (022, 'THPT Thới Long', '177 Thái Thị Hạnh, khu vực Long Định, phường Long Hưng, quận Ô Môn, TP Cần Thơ', '04', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (025, 'THPT Lương Định Của', 'Khu vực 13, phường Châu Văn Liêm, quận Ô Môn, TP Cần Thơ', '04', 360);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (028, 'THPT Phan Văn Trị', 'Thị trấn Phong Điền, huyện Phong Điền, TP Cần Thơ', '05', 560);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (058, 'THPT Giai Xuân', 'Tỉnh lộ 918, ấp Thới An A, xã Giai Xuân, huyện Phong Điền, TP Cần Thơ', '05', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (040, 'THPT Trung An', 'Ấp Thạnh Lộc 2, xã Trung An, huyện Cờ Đỏ, TP Cần Thơ', '06', 469);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (032, 'THPT Hà Huy Giáp', 'Ấp Thới Bình, thị trấn Cờ Đỏ, huyện Cờ Đỏ, TP Cần Thơ', '06', 487);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (023, 'THCS và THPT Trần Ngọc Hoằng', 'Ấp 2, xã Thới Hưng, huyện Cờ Đỏ, TP Cần Thơ', '06', 152);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (035, 'THPT Thạnh An', 'Ấp Phụng Qưới A, thị trấn Thạnh An, huyện Vĩnh Thạnh, TP Cần Thơ', '07', 450);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (045, 'THPT Vĩnh Thạnh', 'Thị trấn Vĩnh Thạnh, huyện Vĩnh Thạnh, TP Cần Thơ', '07', 420);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (077, 'THCS và THPT Thạnh Thắng', 'Xã Thạnh Thắng, huyện Vĩnh Thạnh, TP Cần Thơ', '07', 180);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (078, 'THCS và THPT Thới Thuận', 'Quốc lộ 80, khu vực Thới Hòa 2, phường Thới Thuận, quận Thốt Nốt, TP Cần Thơ', '08', 250);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (079, 'THCS và THPT Tân Lộc', 'Khu vực Phước Lộc, phường Tân Lộc, quận Thốt Nốt, TP Cần Thơ', '08', 265);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (039, 'THPT Thốt Nốt', 'Phường Thuận An, quận Thốt Nốt, TP Cần Thơ', '08', 620);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (041, 'THPT Thuận Hưng', 'Khu vực Tân Phước 1, phường Thuận Hưng, quận Thốt Nốt, TP Cần Thơ', '08', 425);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (059, 'THCS và THPT Trường Xuân', 'Ấp Trường Ninh 1, xã Trường Xuân B, huyện Thới Lai, TP Cần Thơ', '09', 200);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (031, 'THPT Thới Lai', 'Ấp Thới Thuận A, thị trấn Thới Lai, huyện Thới Lai, TP Cần Thơ', '09', 675);
INSERT INTO `NLCN`.`TRUONG_THPT` (`MA_THPT`, `TEN_THPT`, `DIA_CHI`, `MA_QUAN_HUYEN`, `CHI_TIEU`) VALUES (081, 'THCS và THPT Thới Thạnh', 'Ấp Thới Bình B, xã Thới Thạnh, huyện Thới Lai, TP Cần Thơ', '09', 270);
-- Bảng Học sinh
CREATE TABLE IF NOT EXISTS `NLCN`.`HOC_SINH` (
  `MA_HOC_SINH` VARCHAR(20) NOT NULL,
  `HO_TEN_HOC_SINH` VARCHAR(45) NOT NULL,
  `GIOI_TINH` INT NOT NULL,
  `NGAY_SINH` DATE NOT NULL,
  `NOI_SINH` VARCHAR(45) NOT NULL,
  `HO_KHAU_THUONG_TRU` VARCHAR(200) NULL,
  `CHO_O_HIEN_NAY` VARCHAR(200) NULL,
  `NAM_TOT_NGHIEP_THCS` VARCHAR(45) NOT NULL,
  `NGOAI_NGU_DANG_HOC` VARCHAR(45) NOT NULL,
  `NGOAI_NGU_DU_THI` VARCHAR(45) NOT NULL,
  `SO_DIEN_THOAI` VARCHAR(11) NULL,
  `MA_THCS` VARCHAR(5) NOT NULL,
  `TEN_DAN_TOC` VARCHAR(45) NOT NULL,
  `MA_DT_UU_TIEN` INT NOT NULL,
  `MA_DT_KHUYEN_KHICH` INT NOT NULL,
  `DUYET` INT NULL,
  PRIMARY KEY (`MA_HOC_SINH`),
  UNIQUE INDEX `MA_HOC_SINH_UNIQUE` (`MA_HOC_SINH` ASC) VISIBLE,
  INDEX `fk_HOC_SINH_DT_UU_TIEN1_idx` (`MA_DT_UU_TIEN` ASC) VISIBLE,
  INDEX `fk_HOC_SINH_DT_KHUYEN_KHICH1_idx` (`MA_DT_KHUYEN_KHICH` ASC) VISIBLE,
  INDEX `fk_HOC_SINH_TRUONG_THCS1_idx` (`MA_THCS` ASC) VISIBLE,
  INDEX `fk_HOC_SINH_DAN_TOC1_idx` (`TEN_DAN_TOC` ASC) VISIBLE,
  FULLTEXT INDEX `idx_HO_TEN_HOC_SINH` (`HO_TEN_HOC_SINH`) VISIBLE,
  CONSTRAINT `fk_HOC_SINH_DT_UU_TIEN1`
    FOREIGN KEY (`MA_DT_UU_TIEN`)
    REFERENCES `NLCN`.`DT_UU_TIEN` (`MA_DT_UU_TIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOC_SINH_DT_KHUYEN_KHICH1`
    FOREIGN KEY (`MA_DT_KHUYEN_KHICH`)
    REFERENCES `NLCN`.`DT_KHUYEN_KHICH` (`MA_DT_KHUYEN_KHICH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOC_SINH_TRUONG_THCS1`
    FOREIGN KEY (`MA_THCS`)
    REFERENCES `NLCN`.`TRUONG_THCS` (`MA_THCS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOC_SINH_DAN_TOC1`
    FOREIGN KEY (`TEN_DAN_TOC`)
    REFERENCES `NLCN`.`DAN_TOC` (`TEN_DAN_TOC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- Bảng Kết quả học tập
CREATE TABLE IF NOT EXISTS `NLCN`.`KQ_HOC_TAP` (
  `MA_HOC_SINH` VARCHAR(20) NOT NULL,
  `LOP` INT NOT NULL,
  `HOC_LUC` VARCHAR(45) NOT NULL,
  `HANH_KIEM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MA_HOC_SINH`, `LOP`),
  CONSTRAINT `fk_KQ_HOC_TAP_HOC_SINH1`
    FOREIGN KEY (`MA_HOC_SINH`)
    REFERENCES `NLCN`.`HOC_SINH` (`MA_HOC_SINH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- Bảng Nguyện vọng
CREATE TABLE IF NOT EXISTS `NLCN`.`NGUYEN_VONG` (
  `MA_HOC_SINH` VARCHAR(20) NOT NULL,
  `MA_THPT` VARCHAR(3) NOT NULL,
  `THU_TU` INT NOT NULL,
  `LOP_CHUYEN` VARCHAR(45) NULL,
  `MON_CHUYEN` VARCHAR(45) NULL,
  PRIMARY KEY (`MA_HOC_SINH`, `MA_THPT`),
  INDEX `fk_NGUYEN_VONG_TRUONG_THPT1_idx` (`MA_THPT` ASC) VISIBLE,
  CONSTRAINT `fk_NGUYEN_VONG_HOC_SINH1`
    FOREIGN KEY (`MA_HOC_SINH`)
    REFERENCES `NLCN`.`HOC_SINH` (`MA_HOC_SINH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NGUYEN_VONG_TRUONG_THPT1`
    FOREIGN KEY (`MA_THPT`)
    REFERENCES `NLCN`.`TRUONG_THPT` (`MA_THPT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- Bảng Thí sinh
CREATE TABLE IF NOT EXISTS `NLCN`.`THI_SINH` (
  `MA_HOC_SINH` VARCHAR(20) NOT NULL,
  `MA_THPT` VARCHAR(3) NOT NULL,
  `SO_BAO_DANH` VARCHAR(45) NULL,
  `PHONG_THI` INT NULL,
  `DIEM_TOAN` DOUBLE NULL,
  `DIEM_NGOAI_NGU` DOUBLE NULL,
  `DIEM_NGU_VAN` DOUBLE NULL,
  `DIEM_MON_CHUYEN` DOUBLE NULL,
  PRIMARY KEY (`MA_HOC_SINH`),
  INDEX `fk_THI_SINH_TRUONG_THPT1_idx` (`MA_THPT` ASC) VISIBLE,
  UNIQUE INDEX `SO_BAO_DANH_UNIQUE` (`SO_BAO_DANH` ASC) VISIBLE,
  CONSTRAINT `fk_THI_SINH_HOC_SINH1`
    FOREIGN KEY (`MA_HOC_SINH`)
    REFERENCES `NLCN`.`HOC_SINH` (`MA_HOC_SINH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_THI_SINH_TRUONG_THPT1`
    FOREIGN KEY (`MA_THPT`)
    REFERENCES `NLCN`.`TRUONG_THPT` (`MA_THPT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- Bảng Tài khoản
CREATE TABLE IF NOT EXISTS `NLCN`.`TAI_KHOAN` (
  `TEN_TAI_KHOAN` VARCHAR(45) NOT NULL,
  `MAT_KHAU` VARCHAR(45) NOT NULL,
  `DOI_TUONG` VARCHAR(45) NOT NULL,
  `MA_TRUONG` VARCHAR(10) NULL,
  PRIMARY KEY (`TEN_TAI_KHOAN`),
  UNIQUE INDEX `TEN_TAI_KHOAN_UNIQUE` (`TEN_TAI_KHOAN` ASC) VISIBLE)
ENGINE = InnoDB;
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('admin', 'admin', 'admin', NULL);
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('sgddt', 'sgddt', 'sgddt', NULL);
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('nk-thcsltv', 'nk-thcsltv', 'thcs', '01008');
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('nk-thcsdtd', 'nk-thcsdtd', 'thcs', '01006');
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('cr-thptcltt', 'cr-thptcltt', 'thpt', '013');
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('nk-thptthsp', 'nk-thptthsp', 'thpt', '063');
INSERT INTO `NLCN`.`TAI_KHOAN` (`TEN_TAI_KHOAN`, `MAT_KHAU`, `DOI_TUONG`, `MA_TRUONG`) VALUES ('092209000001', '123456', 'hocsinh', NULL);
